version: '3.8'

services:
  db:
    image: mysql:8-debian
    volumes:
      - db_data:/var/lib/mysql
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: DockerfileWordPress
    ports:
      - "${WORDPRESS_PORT}:80"
    container_name: "wp6-training"
    restart: "no"
    networks:
      - wpsite
    volumes:
      -  ./htdocs:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: db
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data: {}